USE [master]
GO
/****** Object:  Database [SmartMeterDB]    Script Date: 6/5/2024 4:46:20 PM ******/
CREATE DATABASE [SmartMeterDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SmartMeterDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\SmartMeterDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SmartMeterDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\SmartMeterDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SmartMeterDB] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SmartMeterDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SmartMeterDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SmartMeterDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SmartMeterDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SmartMeterDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SmartMeterDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [SmartMeterDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SmartMeterDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SmartMeterDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SmartMeterDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SmartMeterDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SmartMeterDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SmartMeterDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SmartMeterDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SmartMeterDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SmartMeterDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SmartMeterDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SmartMeterDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SmartMeterDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SmartMeterDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SmartMeterDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SmartMeterDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SmartMeterDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SmartMeterDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SmartMeterDB] SET  MULTI_USER 
GO
ALTER DATABASE [SmartMeterDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SmartMeterDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SmartMeterDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SmartMeterDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SmartMeterDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SmartMeterDB] SET QUERY_STORE = OFF
GO
USE [SmartMeterDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [SmartMeterDB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 6/5/2024 4:46:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MeterData]    Script Date: 6/5/2024 4:46:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MeterData](
	[Id] [uniqueidentifier] NOT NULL,
	[MeterSerialNumber] [varchar](8) NOT NULL,
	[MeasurementTime] [datetime] NOT NULL,
	[LastIndex] [decimal](18, 2) NOT NULL,
	[Voltage] [decimal](18, 2) NOT NULL,
	[Current] [decimal](18, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reports]    Script Date: 6/5/2024 4:46:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reports](
	[Id] [uniqueidentifier] NOT NULL,
	[RequestDate] [datetime] NOT NULL,
	[Status] [varchar](50) NOT NULL,
	[Content] [nvarchar](max) NOT NULL,
	[MeterSerialNumber] [varchar](8) NOT NULL,
	[Url] [varchar](max) NOT NULL,
 CONSTRAINT [PK__Reports__3214EC078E1141EC] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[MeterData] ADD  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[Reports] ADD  CONSTRAINT [DF__Reports__Id__267ABA7A]  DEFAULT (newid()) FOR [Id]
GO
USE [master]
GO
ALTER DATABASE [SmartMeterDB] SET  READ_WRITE 
GO
